
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";
/* import { Suspense } from "react";
import Loading from "./loading";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import Error from "./error"; */

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sushi App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={' oper'}>
        <Navbar/>
        <main className=" max-w-7xl mx-auto">
            {children}
        </main>
        <Footer/>
        </body>
    </html>
  );
}
